-- Renomear colunas PT -> EN na tabela clientes
ALTER TABLE clientes RENAME COLUMN nome     TO name;
ALTER TABLE clientes RENAME COLUMN senha    TO password;
ALTER TABLE clientes RENAME COLUMN telefone TO phone;
ALTER TABLE clientes RENAME COLUMN endereco TO address;
ALTER TABLE clientes RENAME COLUMN cidade   TO city;
ALTER TABLE clientes RENAME COLUMN estado   TO state;
ALTER TABLE clientes RENAME COLUMN ativo    TO active;

-- (opcional) garantir defaults/constraints se quiser
-- ALTER TABLE clientes ALTER COLUMN active SET DEFAULT true;
-- CREATE UNIQUE INDEX IF NOT EXISTS uk_client_username ON clientes(username);
-- CREATE UNIQUE INDEX IF NOT EXISTS uk_client_email    ON clientes(email);

CREATE SEQUENCE IF NOT EXISTS clientes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS item_pedido_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pagamento_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pedido_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE clientes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ativo      BOOLEAN                                 NOT NULL,
    cep        VARCHAR(255),
    cidade     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255),
    endereco   VARCHAR(255),
    estado     VARCHAR(255),
    nome       VARCHAR(255),
    senha      VARCHAR(100),
    telefone   VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255),
    CONSTRAINT clientes_pkey PRIMARY KEY (id)
);

CREATE TABLE item_pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    discount_price numeric(38, 2),
    nome_produto   VARCHAR(255),
    preco_pago     numeric(38, 2),
    preco_unitario numeric(38, 2),
    quantidade     INTEGER,
    pedido_id      BIGINT,
    produto_id     BIGINT,
    CONSTRAINT item_pedido_pkey PRIMARY KEY (id)
);

CREATE TABLE pagamento
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_pagamento TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    valor          numeric(38, 2)                          NOT NULL,
    pedido_id      BIGINT                                  NOT NULL,
    CONSTRAINT pagamento_pkey PRIMARY KEY (id)
);

CREATE TABLE pedido
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cancelado   BOOLEAN                                 NOT NULL,
    date_create TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    total       numeric(38, 2)                          NOT NULL,
    cliente_id  BIGINT                                  NOT NULL,
    CONSTRAINT pedido_pkey PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao           VARCHAR(255),
    discount_percentage DOUBLE PRECISION                        NOT NULL,
    discounted_price    numeric(38, 2),
    estoque             INTEGER,
    nome                VARCHAR(255),
    preco               numeric(38, 2),
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

ALTER TABLE item_pedido
    ADD CONSTRAINT fk60ym08cfoysa17wrn1swyiuda FOREIGN KEY (pedido_id) REFERENCES pedido (id) ON DELETE NO ACTION;

ALTER TABLE item_pedido
    ADD CONSTRAINT fk66b72x5w3d875fgt31hku24xd FOREIGN KEY (produto_id) REFERENCES products (id) ON DELETE NO ACTION;

ALTER TABLE pedido
    ADD CONSTRAINT fkdaj89qjvckr7m387qpkvuqw5s FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE NO ACTION;

ALTER TABLE pagamento
    ADD CONSTRAINT fkthad9tkw4188hb3qo1lm5ueb0 FOREIGN KEY (pedido_id) REFERENCES pedido (id) ON DELETE NO ACTION;